[llm]
model = "gpt-4.1"
base_url = "https://api.openai.com/v1"
api_key = "${OPENAI_API_KEY}"
max_tokens = 8192
temperature = 0.0

[llm_claude]
model = "claude-3-opus-20240229"
base_url = "https://api.anthropic.com/v1/"
api_key = "${CLAUDE_API_KEY}"
max_tokens = 8192
temperature = 0.0

[llm_gemini]
model = "gemini-1.5-pro-latest"
base_url = "https://generativelanguage.googleapis.com/v1beta/models"
api_key = "${GEMINI_API_KEY}"
max_tokens = 8192
temperature = 0.0

[llm_openai]
model = "gpt-4o"
base_url = "https://api.openai.com/v1"
api_key = "${OPENAI_API_KEY}"
max_tokens = 8192
temperature = 0.0
